# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# maven/BMI-Calculator/azure-pipelines.yml

trigger:
  branches:
    include:
      - main              # change if you use another branch
  paths:
    include:
      - maven/BMI-Calculator/**   # run only when files here change

pool:
  name: Default 
  demands:
    - Agent.Name -equals    DESKTOP-8OLSUHU # target this specific machine 

steps:
# Build & test with Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'maven/BMI-Calculator/pom.xml'
    goals: 'clean test'                   # regression tests
    javaHomeOption: 'Path'
    jdkDirectory: 'C:/Program Files/Java/jdk-24.0.2'   # <-- set to your real JDK 
    mavenVersionOption: 'Default'
    publishJUnitResults: true

# Publish build output as artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish build artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/maven/BMI-Calculator/target'
    artifact: 'maven-build'
    publishLocation: 'pipeline'
