# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'   # Microsoft-hosted agent

steps:
# Select Java version (11 here, change if you need 17 or 21)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Build & test with Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'maven/BMI-Calculator/pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenVersionOption: 'Default'
