# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - maven/BMI-Calculator/**

pool:
  vmImage: 'ubuntu-latest'   # Microsoft-hosted agent

steps:
# Install specific JDK
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '24'       # change to 21 if your Maven project needs JDK 21
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Build & test with Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'maven/BMI-Calculator/pom.xml'
    goals: 'clean test'
    mavenVersionOption: 'Default'
    publishJUnitResults: true

# Publish build output as artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish build artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/maven/BMI-Calculator/target'
    artifact: 'maven-build'
    publishLocation: 'pipeline'
